#!/usr/bin/env bash
# =============================================================================
# Every training knob lives here. Sourced by both experiments/lib/common.sh
# and run_loop.sh, so main / baseline / ablation exps all start from exactly
# the same trainer config — exps should differ only in reward config and
# which stages run, never in lr / lengths / sampling.
#
# Usage: source this file -> override the variables you want -> call
# build_grpo_extra etc. to assemble the args. Every variable uses `:=`, so
# values set before sourcing win (in-script overrides go after the source).
# =============================================================================

# --- GRPO ---
: "${GRPO_LR:=1e-6}"
: "${GRPO_WARMUP_RATIO:=0.1}"
: "${GRPO_LR_SCHEDULER:=cosine}"
: "${GRPO_BETA:=0.06}"                # KL coefficient
: "${GRPO_WEIGHT_DECAY:=0.0}"
: "${GRPO_TEMPERATURE:=1.0}"          # rollout temperature; lower = more homogeneous groups
# Must hold num_players images at GRPO_MIN_PIXELS, plus the prompt text —
# visual tokens are 28x28 pixels each. Too small and the images are silently
# truncated; the loop warns at launch when the combination does not fit.
: "${GRPO_MAX_PROMPT_LEN:=10240}"
# The library default is 256: a five-image comparison CoT doesn't fit, and the
# trailing <bbox> block is what gets truncated first — so set this explicitly.
: "${GRPO_MAX_COMPLETION_LEN:=1024}"
# Resolution the solver sees. Pick it with
# experiments/analysis/perception_probe.sh for your model and image pool; the
# library default is far too low for these scenes. Raising it also raises
# GRPO_MAX_PROMPT_LEN, since the images have to fit in the prompt.
: "${GRPO_MIN_PIXELS:=802816}"        # 1024*28*28
: "${GRPO_MAX_PIXELS:=1003520}"       # 1280*28*28
# Advantages subtract the group mean but don't divide by std (Dr. GRPO).
# Dividing re-inflates the format-only variance of answer-saturated groups
# back to unit scale.
: "${GRPO_SCALE_REWARDS:=False}"
# Rollouts truncated by max_completion_length (no EOS) get zero advantage.
: "${GRPO_OVERLONG_FILTERING:=True}"
: "${GRPO_DYNAMIC_SAMPLING:=True}"
# mask_degenerate: zero only the degenerate groups' advantages, keep the
#   healthy groups in the same batch.
# batch_retry: resample the whole batch (a collapsed prompt stays degenerate
#   no matter how often you resample — generally avoid).
: "${GRPO_DYNAMIC_MODE:=mask_degenerate}"
: "${GRPO_DYNAMIC_STD_THRESHOLD:=0.02}"
: "${GRPO_DYNAMIC_MAX_RETRIES:=3}"
: "${GRPO_MAX_STEPS:=}"               # empty = each script's MAX_STEPS

# --- SFT ---
: "${SFT_LR:=1e-6}"
: "${SFT_WARMUP_RATIO:=0.0}"
: "${SFT_LR_SCHEDULER:=cosine}"
: "${SFT_PER_DEVICE_BATCH:=8}"
: "${SFT_WEIGHT_DECAY:=0.0}"
: "${SFT_MAX_STEPS:=}"

# --- Main-table protocol ---
# Every exp in the main results table must share these. If two exps differ
# here, the table is comparing training budget or adaptation method, not the
# method itself. Ablations may of course override them.
: "${LOOP_ITERATIONS:=1}"                                        # self-evolve rounds
: "${GRPO_STEPS_PER_ITER:=320}"                                  # GRPO steps per round
: "${TOTAL_GRPO_STEPS:=$((LOOP_ITERATIONS * GRPO_STEPS_PER_ITER))}"  # what a single-round exp must match
: "${MAIN_NUM_GENERATIONS:=16}"                                  # GRPO group size
: "${MAIN_NUM_TRAIN_TASKS:=256}"                                 # candidate tasks per round
: "${MAIN_USE_LORA:=0}"                                          # 0 = full-parameter everywhere

# --- Which training stages run ---
# Comma-separated, executed in sft -> grpo order; GRPO starts from the SFT
# checkpoint. This is the only thing ablation exps should vary (the other is
# REWARD_JSON).
: "${STAGES:=sft,grpo}"

# --- Task generation ---
# Fraction of each round generated by editing the previous round's
# highest-regret scenes; the rest is freshly sampled. 0 = no editing, pure
# sampling.
: "${EDIT_FRACTION:=0.5}"
# Edited variants come in pairs (one object apart), used to measure
# counterfactual sensitivity.
: "${COUNTERFACTUAL_PAIRS:=1}"
# uniform = flatten the gold changed_attributes distribution at generation
# time; none = whatever the pool happens to contain.
: "${LABEL_BALANCE:=uniform}"

# --- Self-play ---
# The model picks which changes to keep, then solves what it picked, and is
# trained on the picks the solver found learnable. Each proposal takes one task
# slot, so turning this on does not change the solver rollout budget.
: "${SELF_PLAY:=1}"
: "${PROPOSER_GROUP_SIZE:=4}"        # proposals per scene
: "${PROPOSER_MAX_SCENES:=8}"        # scenes proposed over per round
: "${PROPOSER_TEMPERATURE:=1.0}"
: "${PROPOSER_MAX_NEW_TOKENS:=512}"
# Lowest realized learnability a proposal must reach to be trained on.
# 0.5 means the solver's pass rate landed roughly between 0.15 and 0.85.
: "${PROPOSER_LEARNABILITY_THRESHOLD:=0.5}"
# 1 hides the solver's current solve rate from the proposer (ablation).
: "${PROPOSER_NO_COMPETENCE:=0}"
# The proposer's second axis. The CLEVR pool has 2 changed objects in every
# scene, so the subset choice alone is only 3 options; the player count is what
# makes the action space big enough to be a game. The spy slot stays random —
# it is the answer, and a proposer that could pick it would let both roles
# settle on one constant slot.
: "${PROPOSER_MIN_PLAYERS:=3}"
: "${PROPOSER_MAX_PLAYERS:=8}"

# --- Offline solver rollouts (the scoring / buffer-building pass) ---
# Length must match GRPO; too low a temperature (e.g. 0.2) makes the group
# nearly identical and every advantage 0.
: "${SOLVER_MAX_NEW_TOKENS:=1024}"
: "${SOLVER_TEMPERATURE:=1.0}"
: "${SOLVER_TOP_P:=0.95}"

# --- Shared by all stages ---
# Non-reentrant checkpointing: under 8-card DDP, reentrant marks the same
# parameter ready twice.
: "${GC_KWARGS:=--gradient_checkpointing_kwargs '{\"use_reentrant\": false}'}"
: "${CLIP:=--max_grad_norm 0.3}"
: "${SAVE_STEPS:=10}"

build_grpo_extra() {
  local steps=""
  [ -n "${GRPO_MAX_STEPS:-}" ] && steps="--max_steps $GRPO_MAX_STEPS"
  echo "$steps --learning_rate $GRPO_LR --warmup_ratio $GRPO_WARMUP_RATIO" \
       "--lr_scheduler_type $GRPO_LR_SCHEDULER --beta $GRPO_BETA" \
       "--max_prompt_length $GRPO_MAX_PROMPT_LEN" \
       "--max_completion_length $GRPO_MAX_COMPLETION_LEN" \
       "--min_pixels $GRPO_MIN_PIXELS --max_pixels $GRPO_MAX_PIXELS" \
       "--weight_decay $GRPO_WEIGHT_DECAY --temperature $GRPO_TEMPERATURE" \
       "--scale_rewards $GRPO_SCALE_REWARDS" \
       "--overlong_filtering $GRPO_OVERLONG_FILTERING" \
       "--dynamic_sampling $GRPO_DYNAMIC_SAMPLING" \
       "--dynamic_sampling_mode $GRPO_DYNAMIC_MODE" \
       "--dynamic_sampling_std_threshold $GRPO_DYNAMIC_STD_THRESHOLD" \
       "--dynamic_sampling_max_retries $GRPO_DYNAMIC_MAX_RETRIES" \
       "--save_steps $SAVE_STEPS $CLIP $GC_KWARGS"
}

build_sft_extra() {
  local steps=""
  [ -n "${SFT_MAX_STEPS:-}" ] && steps="--max_steps $SFT_MAX_STEPS"
  echo "$steps --learning_rate $SFT_LR --warmup_ratio $SFT_WARMUP_RATIO" \
       "--lr_scheduler_type $SFT_LR_SCHEDULER" \
       "--per_device_train_batch_size $SFT_PER_DEVICE_BATCH" \
       "--weight_decay $SFT_WEIGHT_DECAY --save_steps 2 $CLIP $GC_KWARGS"
}


# Assemble the per-stage extra args and export them (the loop entry reads
# these environment variables).
export_train_extra_args() {
  export SELF_EVOLVE_GRPO_EXTRA_ARGS="$(build_grpo_extra)"
  export SELF_EVOLVE_SFT_EXTRA_ARGS="$(build_sft_extra)"
}

# $STAGES -> the loop's --execute-*-smoke flags.
stage_cli_args() {
  local out=""
  case ",$STAGES," in *,sft,*)  out="$out --execute-sft-smoke";; esac
  case ",$STAGES," in *,grpo,*) out="$out --execute-grpo-smoke";; esac
  [ -n "$out" ] || { echo "[ERROR] STAGES=$STAGES contains no valid training stage" >&2; return 2; }
  echo "$out"
}

# CLI flags for the offline solver rollouts, appended to the loop's ARGS.
solver_cli_args() {
  echo "--solver-max-new-tokens $SOLVER_MAX_NEW_TOKENS" \
       "--solver-temperature $SOLVER_TEMPERATURE" \
       "--solver-top-p $SOLVER_TOP_P" \
       "--solver-min-pixels $GRPO_MIN_PIXELS" \
       "--solver-max-pixels $GRPO_MAX_PIXELS"
}

# Task-generation CLI flags.
generator_cli_args() {
  local out="--edit-fraction $EDIT_FRACTION --label-balance $LABEL_BALANCE"
  [ "$COUNTERFACTUAL_PAIRS" = "1" ] || out="$out --no-counterfactual-pairs"
  if [ "$SELF_PLAY" = "1" ]; then
    out="$out --self-play"
    out="$out --proposer-group-size $PROPOSER_GROUP_SIZE"
    out="$out --proposer-max-scenes $PROPOSER_MAX_SCENES"
    out="$out --proposer-temperature $PROPOSER_TEMPERATURE"
    out="$out --proposer-max-new-tokens $PROPOSER_MAX_NEW_TOKENS"
    out="$out --proposer-learnability-threshold $PROPOSER_LEARNABILITY_THRESHOLD"
    out="$out --proposer-min-players $PROPOSER_MIN_PLAYERS"
    out="$out --proposer-max-players $PROPOSER_MAX_PLAYERS"
    [ "$PROPOSER_NO_COMPETENCE" = "1" ] && out="$out --proposer-no-competence"
  fi
  echo "$out"
}
